#!/bin/sh -e

if [ -d /root/project-keys ] ; then
    for key_file in `find /root/project-keys -type f`; do
        filename="${key_file##*/}"
        project="${filename%.*}"
        gcloud auth activate-service-account \
            --key-file "${key_file}" \
            --project "${project}"
    done
fi
