#!/bin/sh -e

if [ -d /root/project-keys ] ; then
    for key_file in `find /root/project-keys -type f -name \*.json`; do
        filename="${key_file##*/}"
        project="${filename%.*}"
        gcloud auth activate-service-account \
            --key-file "${key_file}" \
            --project "${project}"
    done
    for key_file in `find /root/project-keys -type f -name \*.p12`; do
        path="${key_file%/*}"
        filename="${key_file##*/}"
        project="${filename%.*}"
        gcloud auth activate-service-account \
            `cat "${path}/${project}.account"` \
            --key-file "${key_file}" \
            --project "${project}"
    done
fi
